#Python List Vs NumPy

In [46]:
import numpy as np
numbers = [1, 2, 3, 4, 5]
arr = np.array(numbers)
# Single dimensional array
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a)
print(b)
print("Addition of a and b:", a + b)  # Element-wise addition
print("Multiplication of a and b:", a * b)
print("Subtraction of a and b:", a - b)  # Element-wise subtraction
print("Division of a and b:", a / b)  # Element-wise division

# Multi-dimensional array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(a)
print(b)
print("Addition of a and b:\n", a + b)  # Element-wise addition
print("Multiplication of a and b:\n", a * b)  # Element-wise
print("Subtraction of a and b:\n", a - b)  # Element-wise subtraction
print("Division of a and b:\n", a / b)  # Element-wise division

[1 2 3 4 5]
[ 6  7  8  9 10]
Addition of a and b: [ 7  9 11 13 15]
Multiplication of a and b: [ 6 14 24 36 50]
Subtraction of a and b: [-5 -5 -5 -5 -5]
Division of a and b: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
Addition of a and b:
 [[ 8 10 12]
 [14 16 18]
 [20 22 24]]
Multiplication of a and b:
 [[  7  16  27]
 [ 40  55  72]
 [ 91 112 135]]
Subtraction of a and b:
 [[-6 -6 -6]
 [-6 -6 -6]
 [-6 -6 -6]]
Division of a and b:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]
 [0.53846154 0.57142857 0.6       ]]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)
print("Shape of the array:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type of the array:", arr.dtype)
print("Size of the array:", arr.size)
print("Number of bytes per element:", arr.itemsize)




Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the array: (3, 3)
Number of dimensions: 2
Data type of the array: int64
Size of the array: 9
Number of bytes per element: 8


# Calculate Average Stock Proce and daily returns

In [48]:
import yfinance as yf
import numpy as np

tcs = yf.download("TCS.NS", start="2026-01-01", end="2026-05-16")

# Convert the 'Close' column to a NumPy array
close_prices = tcs['Close'].to_numpy()
# Average stock price
average_price = np.mean(close_prices)
print("Average TCS Close Stock Price:", average_price)
# Higest Price
highest_price = np.max(close_prices)
print("Highest TCS Close Stock Price:", highest_price)
# Lowest Price
lowest_price = np.min(close_prices)
print("Lowest TCS Close Stock Price:", lowest_price)

# Standard Deviation
std_dev = np.std(close_prices)
print("Standard Deviation of TCS Close Stock Prices:", std_dev)
# Calculate the 5-day moving average



[*********************100%***********************]  1 of 1 completed

Average TCS Close Stock Price: 2698.4723047948146
Highest TCS Close Stock Price: 3236.75927734375
Lowest TCS Close Stock Price: 2246.0
Standard Deviation of TCS Close Stock Prices: 312.1198491871158


In [49]:
# Calculate Sales Analysis
sales_data = np.array([100, 150, 200, 250, 300])
total_sales = np.sum(sales_data)
average_sales = np.mean(sales_data)
print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
print("Maximum Sales:", np.max(sales_data))
print("Minimum Sales:", np.min(sales_data))

Total Sales: 1000
Average Sales: 200.0
Maximum Sales: 300
Minimum Sales: 100


In [50]:
import numpy as np
# Simulate grayscale image data (5x5 pixels)
image_data = np.array([[0, 255, 255, 0, 0],
                       [255, 255, 255, 255, 0],
                       [255, 255, 255, 255, 0],
                       [0, 255, 255, 0, 0],
                       [0, 0, 0, 0, 0]])
print("Original Image Data:\n", image_data)
brightened_image = np.clip(image_data + 50, 0, 255)
print("Brightened Image Data:\n", brightened_image)


Original Image Data:
 [[  0 255 255   0   0]
 [255 255 255 255   0]
 [255 255 255 255   0]
 [  0 255 255   0   0]
 [  0   0   0   0   0]]
Brightened Image Data:
 [[ 50 255 255  50  50]
 [255 255 255 255  50]
 [255 255 255 255  50]
 [ 50 255 255  50  50]
 [ 50  50  50  50  50]]


In [51]:
#create array with all zeros
zeros_array = np.zeros((3, 3))
print("Zeros Array:\n", zeros_array)
onces_array = np.ones((2, 4))
print("Ones Array:\n", onces_array)
# Random array
random_array = np.random.rand(3, 3)
print("Random Array:\n", random_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random Array:
 [[0.69557836 0.85203032 0.96551007]
 [0.88143443 0.21685841 0.60851042]
 [0.15722681 0.49666242 0.31838124]]
